#!/usr/bin/env node

var version = require('./package.json').version;
var follow = process.argv.indexOf('-f') > -1;
var requiredModules = [
    'mproj',
    'buffer',
    'iconv-lite',
    'fs',
    'flatbush',
    'rw',
    'path',
    'd3-dsv'
  ];


require("catty")({follow: follow})
  .addLibrary("src")
  .cat("src/gui/mapshaper-gui.js", './www/mapshaper-gui.js')
  .prepend("VERSION = '" + version + "';")
  .cat("src/mapshaper.js", onCat);


require('browserify')('./mapshaper.js', { standalone: 'mapshaperEs' })
require('browserify')()	.bundle(function(err, buf) {
  .require(requiredModules)	  if (err) throw err;
  .bundle(function(err, buf) {	  write('./www/mapshaper.js', buf);
    if (err) throw err;	});


function onCat(err, js) {
  if (!err) {
    write('./mapshaper.js', js);
    write('./www/mapshaper.js', js);
  }
}

function write(ofile, contents) {
  require('fs').writeFileSync(ofile, contents, 'utf-8');
  console.log('Wrote', ofile);
}
